# Generated by Django 5.2.17 on 2026-09-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='tags',
            new_name='category',
        ),
    ]
