# Generated by Django 5.2.17 on 2026-09-28 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_experience_ended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
